# PlayerShops64 v0.0.0-beta by @tbm00
# https://github.com/tbm00/PlayerShops64

enabled: true

mysql:
  host: 'host'
  port: 3306
  database: 'db'
  username: 'user'
  password: 'pass'
  useSSL: false
  hikari:
    maximumPoolSize: 16
    minimumPoolSize: 2
    idleTimeout: 240 # 4 minutes
    connectionTimeout: 30 # 30 seconds
    maxLifetime: 1800 # 30 minutes
    leakDetection:
      enabled: false
      threshold: 2 # 2 seconds

lang:
  prefix: "&8[&fShop&8] &7"

display:
  tick-cycle: 5
  view-distance: 16
  focus-distance: 5
  glass-scale: 0.7
  item-scale: 1.0
  holo-color: "60,0,0,0" # ARGB(%,R,G,B)