name: PlayerShops64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.papermc.playershops64.PlayerShops64
api-version: 1.21.4
depend: [Vault]
softdepend: [DisplayShops, ShopGUIPlus]
commands:
  shop:
    description: Base player command for PlayerShops64
  shopadmin:
    description: Base admin command for PlayerShops64
  sellgui:
    description: Open a GUI to sell items to the best-priced avaliable shops
  depositgui:
    description: Open a GUI to deposit items into your shops
  exchangesellwand:
    description: Exchange Zach_FR's sellwand for PlayerShops64 sellwand
permissions:
  playershops64.player:
    description: Ability to use player commands & features
    default: true
  playershops64.admin:
    description: Ability to use admin commands & features
    default: op